baseURL = 'https://dustinmichels.com'
languageCode = 'en-us'
title = 'Dustin Michels'
theme = 'personal'

[params]
hero_title = "Hi, I'm <span class=\"text-green-600\">Dustin!</span>"
hero_subtitle = "Cyclist, software engineer, and urban planning master’s student <span class=\"text-blue-600 font-bold\">@ Tufts</span>."
mission_title = "Current Mission:"
mission_text = "Designing child-friendly cities and child-empowering urban design.<span class=\"block mt-2 font-semibold\">Kids, bikes, and kids on bikes.</span>"
footer_text = "Dustin Michels — Built with Vue & Lots of Pedaling"
tags = ["data", "code", "maps", "transportation", "sustainability", "justice"]

[[menus.main]]
name = "WRITING"
url = "/writing"
weight = 1

[[menus.main]]
name = "PORTFOLIO"
url = "/portfolio"
weight = 2

[[menus.main]]
name = "GAMES"
url = "/games"
weight = 3
