baseURL = 'https://dustinsite.netlify.app'
languageCode = 'en-us'
title = 'Dustin Michels'

[params]
tags = [
    "data",
    "maps",
    "mobility",
    "sustainability",
    "social justice",
    "child development",
    "design",
]
social = [
    { name = "Bluesky", url = "https://bsky.app/profile/dustinmichels.bsky.social" },
    { name = "GitHub", url = "https://github.com/dustinmichels/" },
    { name = "LinkedIn", url = "https://www.linkedin.com/in/dustin-michels/" },
]
hero_name = "Dustin"
hero_subtitle = "Cyclist, software engineer, and urban planning master's student @ Tufts."
mission_title = "Current Focus:"
mission_text = "Safe, sustainable, and child-empowering urban design."
mission_emphasis = "Kids, bikes, and kids on bikes."
footer_text = "Dustin Michels"

[[menus.main]]
name = "HOME"
pageRef = "/"
weight = 10

[[menus.main]]
name = "WRITING"
pageRef = "/writing"
weight = 20

[[menus.main]]
name = "PORTFOLIO"
pageRef = "/portfolio"
weight = 30
