baseURL = 'https://dustinsite.netlify.app'
languageCode = 'en-us'
title = 'Dustin Michels'

[params]
tags = [
    "data",
    "maps",
    "mobility",
    "sustainability",
    "social justice",
    "child development",
]
social = [
    { name = "Bluesky", url = "https://bsky.app/profile/dustinmichels.bsky.social" },
    { name = "GitHub", url = "https://github.com/dustinmichels/" },
    { name = "LinkedIn", url = "https://www.linkedin.com/in/dustin-michels/" },
]
hero_title = "Hi, I'm <span class=\"text-green-600\">Dustin!</span>"
hero_subtitle = "Cyclist, software engineer, and urban planning master’s student <span class=\"text-blue-600 font-bold\">@ Tufts</span>."
mission_title = "Current Focus:"
mission_text = "Safe, sustainable, and child-empowering urban design.<span class=\"block mt-2 font-semibold\">Kids, bikes, and kids on bikes.</span>"
footer_text = "Dustin Michels"

[[menus.main]]
name = "HOME"
pageRef = "/"
weight = 10

[[menus.main]]
name = "WRITING"
pageRef = "/writing"
weight = 20

[[menus.main]]
name = "PORTFOLIO"
pageRef = "/portfolio"
weight = 30

[[menus.main]]
name = "GAMES"
pageRef = "/games"
weight = 40
